"""initial migration

Revision ID: f8410c2d1f28
Revises: 
Create Date: 2023-05-12 11:35:07.257048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8410c2d1f28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('headlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_index(op.f('ix_headlines_category'), 'headlines', ['category'], unique=False)
    op.create_index(op.f('ix_headlines_sentiment'), 'headlines', ['sentiment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_headlines_sentiment'), table_name='headlines')
    op.drop_index(op.f('ix_headlines_category'), table_name='headlines')
    op.drop_table('headlines')
    # ### end Alembic commands ###
